services:
  - name: n8n
    type: web
    env: docker
    region: frankfurt # This region is optional and defaults to oregon
    plan: free # This plan is optional and defaults to starter
    branch: main # This branch is optional and defaults to master
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: ${DB_POSTGRESDB_HOST}
      - key: DB_POSTGRESDB_DATABASE
        value: ${DB_POSTGRESDB_DATABASE}
      - key: DB_POSTGRESDB_PORT
        value: ${DB_POSTGRESDB_PORT}
      - key: DB_POSTGRESDB_USER
        value: ${DB_POSTGRESDB_USER}
      - key: DB_POSTGRESDB_PASSWORD
        value: ${DB_POSTGRESDB_PASSWORD}
      - key: PORT
        value: 5678
      - key: N8N_LOG_LEVEL
        value: info
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: TZ
        value: Europe/Paris
      - key: N8N_DEFAULT_LOCALE
        value: fr
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: EXECUTIONS_PROCES
        value: main
      - key: WEBHOOK_URL
        value: ${WEBHOOK_URL}
